import logging

LOGGING_LEVEL = logging.CRITICAL

USE_LOCAL_PEERS = False
USE_HTTP_PEERS = True

MAX_PEER_COUNT = 50
MAX_PEER_PEERS_PER_SEGMENT = 1
MAX_SEGMENTS_DOWNLOADING_SIMULTANEOUSLY = 5

MAX_STRIKES_PER_PEER = 5
MAX_PENDING_BLOCKS = 5

WRITE_BUFFER_LENGTH = 2 ** 13
FILES_BUFFER_LENGTH = 10

MAX_PEERS_PENDING = 100
